server:
  port: 8008
  servlet:
    context-path: /
spring:
  application:
    name: collector-log
  http:
    encoding:
      charset: UTF-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null